#ifndef _FLASH_EYES_CORE_LIB_CONFIG_H
#define _FLASH_EYES_CORE_LIB_CONFIG_H

/////////////////////////////////////////////////
// INCLUDE
// 
/////////////////////////////////////////////////
// PREPROCESSOR
// 
//################DEFINE SYSTEM TYPE#######################
#if defined(ARDUINO_ARCH_AVR)
#define SYSTEM_AVR_PLATFORM
#define SYSTEM_ARDUINO_BASED
#elif defined(ARDUINO_ESP32_DEV)
#define SYSTEM_16BIT_SUPPORT
#define SYSTEM_ESP_PLATFORM
#define SYSTEM_ARDUINO_BASED
#elif defined(_WIN32)
#define SYSTEM_WIN_PLATFORM
#define SYSTEM_PC_BASED
#elif defined(Linux)
#define SYSTEM_LINUX_PLATFORM
#define SYSTEM_PC_BASED
#else // unsupported 
#error Not supported platform
#endif // ARDUINO_ESP32_DEV


#ifdef ESP_PLATFORM
#undef __CONF_FREE_RTOS_FUNC_ENABLED
#define __CONF_FREE_RTOS_FUNC_ENABLED
#endif // 

//#define __CONF_SYSTEM_MUTEX_FUNC_ENABLED
//#define __CONF_FREE_RTOS_FUNC_ENABLED

//#define __CONF_COMM_MBC_SERIAL_FUNC_ENABLED
//#define __CONF_COMM_MBC_SERIAL_WITH_TASK_FUNC_ENABLED

//#define __CONF_TASK_MANAGER_FUNC_ENABLED
//#define __CONF_COMM_SERIAL_TASK_FUNC_ENABLED
//#define __CONF_COMM_SERIAL_WITH_TASK_FUNC_ENABLED
//#define __CONF_COMM_MBC_I2C_CLIENT_FUNC_ENABLED
//#define __CONF_COMM_MBC_I2C_SERVER_FUNC_ENABLED

//#define __CONF_SENSOR_TASK_FUNC_ENABLED
//#define __CONF_DISPLAY_TASK_FUNC_ENABLED
//#define __CONF_CONSOLE_TASK_FUNC_ENABLED
#define __CONF_CONSOLE_LOG_FUNC_ENABLED
//#define __CONF_COMM_I2C_CLIENT_FUNC_ENABLED
//#define __CONF_COMM_I2C_SERVER_FUNC_ENABLED
#define __CONF_TASK_MANAGER_FUNC_ENABLED
#define __CONF_TIMER_MANAGER_FUNC_ENABLED

#define __CONF_COMM_MBC_BASE_FUNC_ENABLED

// log
#ifdef __CONF_CONSOLE_LOG_FUNC_ENABLED
#define _CONF_SYSTEM_CONSOLE_LOG_ENABLED          1
#else // __CONF_CONSOLE_LOG_FUNC_ENABLED
#define _CONF_SYSTEM_CONSOLE_LOG_ENABLED          0
#endif // __CONF_CONSOLE_LOG_FUNC_ENABLED

// serial 
#if (_CONF_SYSTEM_CONSOLE_LOG_ENABLED)
#define _CONF_SYSTEM_SERIAL_ENABLED               1
#else // _CONF_SYSTEM_CONSOLE_LOG_ENABLED
#define _CONF_SYSTEM_SERIAL_ENABLED               0
#endif // _CONF_SYSTEM_CONSOLE_LOG_ENABLED


// task_console
#ifdef __CONF_CONSOLE_TASK_FUNC_ENABLED
#define _CONF_CONSOLE_TASK_FUNC_ENABLED_VAL       1
#undef __CONF_TASK_MANAGER_FUNC_ENABLED
#define __CONF_TASK_MANAGER_FUNC_ENABLED
#else // __CONF_CONSOLE_TASK_FUNC_ENABLED
#define _CONF_CONSOLE_TASK_FUNC_ENABLED_VAL       0
#endif // __CONF_CONSOLE_TASK_FUNC_ENABLED

#define _CONF_CONSOLE_LOGGING_CONSTANT_ENABLED    _CONF_CONSOLE_TASK_FUNC_ENABLED_VAL
#define _CONF_CONSOLE_LOGGING_TASK_ENABLED        _CONF_CONSOLE_TASK_FUNC_ENABLED_VAL

// task_display
#ifdef __CONF_DISPLAY_TASK_FUNC_ENABLED
#define _CONF_DISPLAY_TASK_FUNC_ENABLED_VAL       1
#undef __CONF_TASK_MANAGER_FUNC_ENABLED
#define __CONF_TASK_MANAGER_FUNC_ENABLED
#else // __CONF_DISPLAY_TASK_FUNC_ENABLED
#define _CONF_DISPLAY_TASK_FUNC_ENABLED_VAL       0
#endif // __CONF_DISPLAY_TASK_FUNC_ENABLED

#define _CONF_DISPLAY_TASK_COMMON_ENABLED         _CONF_DISPLAY_TASK_FUNC_ENABLED_VAL
#define _CONF_DISPLAY_ENGINE_ENABLED              _CONF_DISPLAY_TASK_FUNC_ENABLED_VAL
#define _CONF_DISPLAY_DEVICE_INFO_ENABLED         _CONF_DISPLAY_TASK_FUNC_ENABLED_VAL
#define _CONF_DISPLAY_DEVICE_CONTROLLER_ENABLED   _CONF_DISPLAY_TASK_FUNC_ENABLED_VAL
#define _CONF_DISPLAY_CONTROL_TASK_ENABLED        _CONF_DISPLAY_TASK_FUNC_ENABLED_VAL


// task_distance_sensor
#ifdef __CONF_SENSOR_TASK_FUNC_ENABLED
#define _CONF_SENSOR_TASK_FUNC_ENABLED_VAL        1
#undef __CONF_TASK_MANAGER_FUNC_ENABLED
#define __CONF_TASK_MANAGER_FUNC_ENABLED
#else // __CONF_SENSOR_TASK_FUNC_ENABLED
#define _CONF_SENSOR_TASK_FUNC_ENABLED_VAL        0
#endif // __CONF_SENSOR_TASK_FUNC_ENABLED

#define _CONF_SENSOR_TASK_COMMON_ENABLED          _CONF_SENSOR_TASK_FUNC_ENABLED_VAL
#define _CONF_SENSOR_ENGINE_ENABLED               _CONF_SENSOR_TASK_FUNC_ENABLED_VAL
#define _CONF_SENSOR_DEVICE_INFO_ENABLED          _CONF_SENSOR_TASK_FUNC_ENABLED_VAL
#define _CONF_SENSOR_DEVICE_CONTROLLER_ENABLED    _CONF_SENSOR_TASK_FUNC_ENABLED_VAL
#define _CONF_SENSOR_CONTROL_TASK_ENABLED         _CONF_SENSOR_TASK_FUNC_ENABLED_VAL


// task_comm_mbc_serial
// with task
#ifdef __CONF_COMM_MBC_SERIAL_WITH_TASK_FUNC_ENABLED
#define __CONF_COMM_SERIAL_WITH_TASK_FUNC_ENABLED
#define __CONF_COMM_MBC_SERIAL_FUNC_ENABLED
#endif // __CONF_COMM_MBC_SERIAL_WITH_TASK_FUNC_ENABLED
// without task
#ifdef __CONF_COMM_MBC_SERIAL_FUNC_ENABLED
#define __CONF_COMM_SERIAL_TASK_FUNC_ENABLED
#define __CONF_COMM_MBC_BASE_FUNC_ENABLED
#define _CONF_COMM_MBC_SERIAL_CONSTANT_ENABLED     1
#define _CONF_COMM_MBC_SERIAL_ENABLED              1
#endif // __CONF_COMM_MBC_SERIAL_FUNC_ENABLED


// task_comm_mbc_i2c
#ifdef __CONF_COMM_MBC_I2C_CLIENT_FUNC_ENABLED
#define _CONF_COMM_MBC_I2C_CONSTANT_ENABLED     1
#define _CONF_COMM_MBC_I2C_CLIENT_ENABLED       1
#define __CONF_COMM_MBC_BASE_FUNC_ENABLED
#define __CONF_COMM_I2C_CLIENT_FUNC_ENABLED
#endif // __CONF_COMM_MBC_I2C_CLIENT_FUNC_ENABLED

#ifdef __CONF_COMM_MBC_I2C_SERVER_FUNC_ENABLED
#define _CONF_COMM_MBC_I2C_CONSTANT_ENABLED     1
#define _CONF_COMM_MBC_I2C_SERVER_ENABLED       1
#define __CONF_COMM_MBC_BASE_FUNC_ENABLED
#define __CONF_COMM_I2C_SERVER_FUNC_ENABLED
#endif // __CONF_COMM_MBC_I2C_SERVER_FUNC_ENABLED

// task_comm_mbc base
#ifdef __CONF_COMM_MBC_BASE_FUNC_ENABLED
#define _CONF_COMM_MBC_BASE_ENABLED_VAL         1
#define __CONF_DATA_MANAGER_FUNC_ENABLED
#else // __CONF_COMM_MBC_BASE_FUNC_ENABLED
#define _CONF_COMM_MBC_BASE_ENABLED_VAL         0
#endif  //__CONF_COMM_MBC_BASE_FUNC_ENABLED

#define _CONF_COMM_MBC_CONSTANT_ENABLED                   _CONF_COMM_MBC_BASE_ENABLED_VAL
#define _CONF_COMM_MBC_SETTING_ENABLED                    _CONF_COMM_MBC_BASE_ENABLED_VAL
#define _CONF_COMM_MBC_ENGINE_ENABLED                     _CONF_COMM_MBC_BASE_ENABLED_VAL
#define _CONF_COMM_MBC_PROCESSOR_ENABLED                  _CONF_COMM_MBC_BASE_ENABLED_VAL
#define _CONF_COMM_MBC_PROCESSOR_FACTORY_ENABLED          _CONF_COMM_MBC_BASE_ENABLED_VAL
#define _CONF_COMM_MBC_PURE_DATA_PROCESSOR_ENABLED        _CONF_COMM_MBC_BASE_ENABLED_VAL
#define _CONF_COMM_MBC_JSON_DATA_PROCESSOR_ENABLED        _CONF_COMM_MBC_BASE_ENABLED_VAL


// task_comm_serial
#ifdef __CONF_COMM_SERIAL_WITH_TASK_FUNC_ENABLED
#define __CONF_COMM_SERIAL_TASK_FUNC_ENABLED
#undef __CONF_TASK_MANAGER_FUNC_ENABLED
#define __CONF_TASK_MANAGER_FUNC_ENABLED
#define _CONF_COMM_SERIAL_WITH_TASK_ENABLED
#endif // __CONF_COMM_SERIAL_WITH_TASK_FUNC_ENABLED

#ifdef __CONF_COMM_SERIAL_TASK_FUNC_ENABLED
#define _CONF_COMM_SERIAL_TASK_FUNC_ENABLED_VAL  1
#undef __CONF_COMM_TASK_FUNC_ENABLED
#define __CONF_COMM_TASK_FUNC_ENABLED
#undef __CONF_DATA_MANAGER_FUNC_ENABLED
#define __CONF_DATA_MANAGER_FUNC_ENABLED
#else // __CONF_COMM_SERIAL_TASK_FUNC_ENABLED
#define _CONF_COMM_SERIAL_TASK_FUNC_ENABLED_VAL  0
#endif // __CONF_COMM_SERIAL_TASK_FUNC_ENABLED

#define _CONF_COMM_SERIAL_CONSTANT_ENABLED      _CONF_COMM_SERIAL_TASK_FUNC_ENABLED_VAL
#define _CONF_COMM_SERIAL_SETTING_ENABLED       _CONF_COMM_SERIAL_TASK_FUNC_ENABLED_VAL
#define _CONF_COMM_SERIAL_SYSTEM_SOCKET_ENABLED _CONF_COMM_SERIAL_TASK_FUNC_ENABLED_VAL
#define _CONF_COMM_SERIAL_SENDER_ENABLED        _CONF_COMM_SERIAL_TASK_FUNC_ENABLED_VAL
#define _CONF_COMM_SERIAL_RECEIVER_ENABLED      _CONF_COMM_SERIAL_TASK_FUNC_ENABLED_VAL
#define _CONF_COMM_SERIAL_ENABLED               _CONF_COMM_SERIAL_TASK_FUNC_ENABLED_VAL
//#define _CONF_COMM_SERIAL_CODEC_ENABLED         _CONF_COMM_SERIAL_TASK_FUNC_ENABLED_VAL

// task_comm_i2c
#ifdef __CONF_COMM_I2C_SERVER_FUNC_ENABLED
#define _CONF_COMM_I2C_SERVER_FUNC_ENABLED_VAL    1
#define __CONF_COMM_I2C_TASK_FUNC_ENABLED
#else // __CONF_COMM_I2C_SERVER_FUNC_ENABLED
#define _CONF_COMM_I2C_SERVER_FUNC_ENABLED_VAL    0
#endif  //__CONF_COMM_I2C_SERVER_FUNC_ENABLED

#ifdef __CONF_COMM_I2C_CLIENT_FUNC_ENABLED
#define _CONF_COMM_I2C_CLIENT_FUNC_ENABLED_VAL    1
#define __CONF_COMM_I2C_TASK_FUNC_ENABLED
#else // __CONF_COMM_I2C_CLIENT_FUNC_ENABLED
#define _CONF_COMM_I2C_CLIENT_FUNC_ENABLED_VAL    0
#endif  //__CONF_COMM_I2C_CLIENT_FUNC_ENABLED


#ifdef __CONF_COMM_I2C_TASK_FUNC_ENABLED
#define _CONF_COMM_I2C_TASK_FUNC_ENABLED_VAL      1
#undef __CONF_COMM_TASK_FUNC_ENABLED
#define __CONF_COMM_TASK_FUNC_ENABLED
#undef __CONF_DATA_MANAGER_FUNC_ENABLED
#define __CONF_DATA_MANAGER_FUNC_ENABLED
#else // __CONF_COMM_I2C_TASK_FUNC_ENABLED
#define _CONF_COMM_I2C_TASK_FUNC_ENABLED_VAL      0
#endif // __CONF_COMM_I2C_TASK_FUNC_ENABLED

#define _CONF_COMM_I2C_CONSTANT_ENABLED           _CONF_COMM_I2C_TASK_FUNC_ENABLED_VAL
#define _CONF_COMM_I2C_COMM_SETTING_ENABLED       _CONF_COMM_I2C_TASK_FUNC_ENABLED_VAL
#define _CONF_COMM_I2C_SYSTEM_SOCKET_ENABLED      _CONF_COMM_I2C_TASK_FUNC_ENABLED_VAL
#define _CONF_COMM_I2C_SOCKET_ENABLED             _CONF_COMM_I2C_TASK_FUNC_ENABLED_VAL
#define _CONF_COMM_I2C_CLIENT_ENABLED             _CONF_COMM_I2C_CLIENT_FUNC_ENABLED_VAL
#define _CONF_COMM_I2C_SERVER_ENABLED             _CONF_COMM_I2C_SERVER_FUNC_ENABLED_VAL

// task comm
#ifdef __CONF_COMM_TASK_FUNC_ENABLED
#define __CONF_TASK_CODEC_FUNC_ENABLED
#define _CONF_COMM_FUNC_ENABLED_VAL               1
#else // __CONF_COMM_TASK_FUNC_ENABLED
#define _CONF_COMM_FUNC_ENABLED_VAL               0
#endif // __CONF_COMM_TASK_FUNC_ENABLED

#define _CONF_COMM_CONSTANT_ENABLED               _CONF_COMM_FUNC_ENABLED_VAL
#define _CONF_COMM_CLIENT_MANAGER_ENABLED         _CONF_COMM_FUNC_ENABLED_VAL


// task_manager
#ifdef __CONF_TASK_MANAGER_FUNC_ENABLED
#define _CONF_TASK_MANAGER_FUNC_ENABLED_VAL       1
#undef __CONF_FREE_RTOS_FUNC_ENABLED
#define __CONF_FREE_RTOS_FUNC_ENABLED
#undef __CONF_EVENT_MANAGER_FUNC_ENABLED
#define __CONF_EVENT_MANAGER_FUNC_ENABLED
#else // __CONF_TASK_MANAGER_FUNC_ENABLED
#define _CONF_TASK_MANAGER_FUNC_ENABLED_VAL       0
#endif // __CONF_TASK_MANAGER_FUNC_ENABLED
#define _CONF_TASK_MANAGER_ENABLED                _CONF_TASK_MANAGER_FUNC_ENABLED_VAL
#define _CONF_TASK_MANAGER_CONSTANT_ENABLED       _CONF_TASK_MANAGER_FUNC_ENABLED_VAL
#define _CONF_TASK_SYSTEM_THREAD_ENABLED          _CONF_TASK_MANAGER_FUNC_ENABLED_VAL
#define _CONF_TASK_THREAD_MANAGER_ENABLED         _CONF_TASK_MANAGER_FUNC_ENABLED_VAL
#define _CONF_TASK_THREAD_POOL_MANAGER_ENABLED    _CONF_TASK_MANAGER_FUNC_ENABLED_VAL

// event_manager
#ifdef __CONF_EVENT_MANAGER_FUNC_ENABLED
#define _CONF_EVENT_MANAGER_FUNC_ENABLED_VAL      1
#undef __CONF_DATA_MANAGER_FUNC_ENABLED
#define __CONF_DATA_MANAGER_FUNC_ENABLED

#undef __CONF_SYSTEM_MUTEX_FUNC_ENABLED
#define __CONF_SYSTEM_MUTEX_FUNC_ENABLED

#else // __CONF_EVENT_MANAGER_FUNC_ENABLED
#define _CONF_EVENT_MANAGER_FUNC_ENABLED_VAL      0
#endif // __CONF_EVENT_MANAGER_FUNC_ENABLED

#define _CONF_EVENT_MANAGER_CONSTANT_ENABLED      _CONF_EVENT_MANAGER_FUNC_ENABLED_VAL
#define _CONF_EVENT_DATA_ITEM_ENABLED             _CONF_EVENT_MANAGER_FUNC_ENABLED_VAL
#define _CONF_EVENT_MANAGER_ENABLED               _CONF_EVENT_MANAGER_FUNC_ENABLED_VAL
#define _CONF_EVENT_POOL_MANAGER_ENABLED          _CONF_EVENT_MANAGER_FUNC_ENABLED_VAL


// timer_manager
#ifdef __CONF_TIMER_MANAGER_FUNC_ENABLED
#define _CONF_TIMER_MANAGER_FUNC_ENABLED_VAL      1
#undef __CONF_SYSTEM_MUTEX_FUNC_ENABLED
#define __CONF_SYSTEM_MUTEX_FUNC_ENABLED
#else // __CONF_TIMER_MANAGER_FUNC_ENABLED
#define _CONF_TIMER_MANAGER_FUNC_ENABLED_VAL      0
#endif // __CONF_TIMER_MANAGER_FUNC_ENABLED

#define _CONF_TIMER_MANAGER_CONSTANT_ENABLED      _CONF_TIMER_MANAGER_FUNC_ENABLED_VAL
#define _CONF_TIMER_CONTROL_TASK_ENABLED          _CONF_TIMER_MANAGER_FUNC_ENABLED_VAL
#define _CONF_TIMER_MANAGER_ENABLED               _CONF_TIMER_MANAGER_FUNC_ENABLED_VAL
#define _CONF_TIMER_CONTROLLER_ENABLED            _CONF_TIMER_MANAGER_FUNC_ENABLED_VAL
#define _CONF_TIMER_DEVICE_TIMER_ENABLED          _CONF_TIMER_MANAGER_FUNC_ENABLED_VAL

// data_manager
#ifdef __CONF_DATA_MANAGER_FUNC_ENABLED
#define _CONF_DATA_MANAGER_FUNC_ENABLED_VAL       1
#else // __CONF_DATA_MANAGER_FUNC_ENABLED
#define _CONF_DATA_MANAGER_FUNC_ENABLED_VAL       0
#endif // __CONF_DATA_MANAGER_FUNC_ENABLED

#define _CONF_DATA_MANAGER_CONSTANT_ENABLED       _CONF_DATA_MANAGER_FUNC_ENABLED_VAL
#define _CONF_DATA_ITEM_ENABLED                   _CONF_DATA_MANAGER_FUNC_ENABLED_VAL
#define _CONF_DATA_QUEUE_ENABLED                  _CONF_DATA_MANAGER_FUNC_ENABLED_VAL
#define _CONF_DATA_MANAGER_ENABLED                _CONF_DATA_MANAGER_FUNC_ENABLED_VAL
#define _CONF_DATA_POOL_MANAGER_TPL_ENABLED       _CONF_DATA_MANAGER_FUNC_ENABLED_VAL
#define _CONF_DATA_POOL_MANAGER_ENABLED           _CONF_DATA_MANAGER_FUNC_ENABLED_VAL
#define _CONF_BUFFER_DATA_MANAGER_ENABLED         _CONF_DATA_MANAGER_FUNC_ENABLED_VAL

// utility
#define _CONF_UTILITY_ENABLED                     1 // always enabled

// json parser
#define _CONF_JSON_PARSER_ENABLED                 1 // always enabled

// task_codec
#ifdef __CONF_TASK_CODEC_FUNC_ENABLED
#define _CONF_TASK_CODEC_FUNC_ENABLED_VAL       1
#else // __CONF_TASK_CODEC_FUNC_ENABLED
#define _CONF_TASK_CODEC_FUNC_ENABLED_VAL       0
#endif // __CONF_TASK_CODEC_FUNC_ENABLED

#define _CONF_TASK_CODEC_CONSTANT_ENABLED       _CONF_TASK_CODEC_FUNC_ENABLED_VAL
#define _CONF_TASK_CODEC_ENABLED                _CONF_TASK_CODEC_FUNC_ENABLED_VAL
// os
#ifdef __CONF_FREE_RTOS_FUNC_ENABLED
#define _CONF_FREE_RTOS_ENABLED                   1
#else // __CONF_FREE_RTOS_FUNC_ENABLED
#define _CONF_FREE_RTOS_ENABLED                   0
#endif // __CONF_FREE_RTOS_FUNC_ENABLED

// os_system
#ifdef __CONF_SYSTEM_MUTEX_FUNC_ENABLED
#define _CONF_SYSTEM_MUTEX_ENABLED                1
#else // __CONF_SYSTEM_MUTEX_FUNC_ENABLED
#define _CONF_SYSTEM_MUTEX_ENABLED                0
#endif // __CONF_SYSTEM_MUTEX_FUNC_ENABLED

//--------------always enabled--------------------
#define _CONF_SYSTEM_CRITICAL_SESSION_ENABLED     1
#define _CONF_SYSTEM_LIGHT_QUEUE_ENABLED          1


/////////////////////////////////////////////////
// DEFINE

/////////////////////////////////////////////////
// GLOBAL VARIABLES

/////////////////////////////////////////////////
// GLOBAL FUNCTIONS

/////////////////////////////////////////////////
// DATA TYPE (TYPEDEF)

/////////////////////////////////////////////////
// DATA TYPE (ENUM)

/////////////////////////////////////////////////
// DATA TYPE (STRUCT)

/////////////////////////////////////////////////
// STATIC DATA

/////////////////////////////////////////////////
// STATIC FUNCTIONS
//

/////////////////////////////////////////////////
// EXTERN

/////////////////////////////////////////////////
// CLASS DEFINITION



#endif // _FLASH_EYES_CORE_LIB_CONFIG_H