#ifndef _FLASH_EYES_MAIN_CONFIG_H
#define _FLASH_EYES_MAIN_CONFIG_H

/////////////////////////////////////////////////
// INCLUDE
// 
/////////////////////////////////////////////////
// PREPROCESSOR
// 
//################DEFINE SYSTEM TYPE#######################
#define __CONF_FILE_SYSTEM_MANAGER_FUNC_ENABLED
#define __CONF_DB_MANAGER_FUNC_ENABLED
#define __CONF_SETTING_MANAGER_FUNC_ENABLED
#define __CONF_NET_MANAGER_FUNC_ENABLED
#define __CONF_NET_WIFI_FUNC_ENABLED
#define __CONF_COMM_HTTP_FUNC_ENABLED
#define __CONF_COMM_MBC_HTTP_FUNC_ENABLED
#define __CONF_EX_COMM_FUNC_ENABLED
#define __CONF_MAIN_CONTROLLER_FUNC_ENABLED
#define __CONF_UI_MANAGER_FUNC_ENABLED
#define __CONF_TASK_SCANNING_FUNC_ENABLED
#define __CONF_TASK_SWITCH_FUNC_ENABLED
#define __CONF_TASK_BUTTON_FUNC_ENABLED

// file system
#ifdef __CONF_FILE_SYSTEM_MANAGER_FUNC_ENABLED
#define CONF_FILE_SYSTEM_MANAGER_FUNC_ENABLED_VAL         1
#else // __CONF_FILE_SYSTEM_MANAGER_FUNC_ENABLED
#define CONF_FILE_SYSTEM_MANAGER_FUNC_ENABLED_VAL         0
#endif // __CONF_FILE_SYSTEM_MANAGER_FUNC_ENABLED

#define _CONF_FILE_SYSTEM_MANAGER_CONSTANT_ENABLED        CONF_FILE_SYSTEM_MANAGER_FUNC_ENABLED_VAL
#define _CONF_FILE_SYSTEM_MANAGER_ENABLED                 CONF_FILE_SYSTEM_MANAGER_FUNC_ENABLED_VAL


// db
#ifdef __CONF_DB_MANAGER_FUNC_ENABLED
#define CONF_DB_MANAGER_FUNC_ENABLED_VAL                  1
#else // __CONF_DB_MANAGER_FUNC_ENABLED
#define CONF_DB_MANAGER_FUNC_ENABLED_VAL                  0
#endif // __CONF_DB_MANAGER_FUNC_ENABLED

#define _CONF_DB_MANAGER_CONSTANT_ENABLED                 CONF_DB_MANAGER_FUNC_ENABLED_VAL
#define _CONF_DB_MANAGER_ENABLED                          CONF_DB_MANAGER_FUNC_ENABLED_VAL

// setting
#ifdef __CONF_SETTING_MANAGER_FUNC_ENABLED
#define CONF_SETTING_MANAGER_FUNC_ENABLED_VAL             1
#else // __CONF_SETTING_MANAGER_FUNC_ENABLED
#define CONF_SETTING_MANAGER_FUNC_ENABLED_VAL             0
#endif // __CONF_SETTING_MANAGER_FUNC_ENABLED

#define _CONF_SETTING_MANAGER_CONSTANT_ENABLED            CONF_SETTING_MANAGER_FUNC_ENABLED_VAL
#define _CONF_SETTING_DEFINITION_ENABLED                  CONF_SETTING_MANAGER_FUNC_ENABLED_VAL
#define _CONF_SETTING_MANAGER_ENABLED                     CONF_SETTING_MANAGER_FUNC_ENABLED_VAL
#define _CONF_SETTING_ITEM_ENABLED                        CONF_SETTING_MANAGER_FUNC_ENABLED_VAL
#define _CONF_SETTING_COLLECTION_ENABLED                  CONF_SETTING_MANAGER_FUNC_ENABLED_VAL
#define _CONF_SCANNER_SETTING_COLLECTION_ENABLED          CONF_SETTING_MANAGER_FUNC_ENABLED_VAL
#define _CONF_SYSTEM_SETTING_COLLECTION_ENABLED           CONF_SETTING_MANAGER_FUNC_ENABLED_VAL
#define _CONF_MAIN_SETTING_COLLECTION_ENABLED             CONF_SETTING_MANAGER_FUNC_ENABLED_VAL
#define _CONF_UI_SETTING_COLLECTION_ENABLED               CONF_SETTING_MANAGER_FUNC_ENABLED_VAL
#define _CONF_SYSTEM_SETTING_DEFINITION_ENABLED           CONF_SETTING_MANAGER_FUNC_ENABLED_VAL

// net
#ifdef __CONF_NET_MANAGER_FUNC_ENABLED
#define CONF_NET_MANAGER_FUNC_ENABLED_VAL                 1
#else // __CONF_NET_MANAGER_FUNC_ENABLED
#define CONF_NET_MANAGER_FUNC_ENABLED_VAL                 0
#endif // __CONF_NET_MANAGER_FUNC_ENABLED

#define _CONF_NET_MANAGER_CONSTANT_ENABLED                CONF_NET_MANAGER_FUNC_ENABLED_VAL
#define _CONF_NET_IP_CONSTANT_ENABLED                     CONF_NET_MANAGER_FUNC_ENABLED_VAL
#define _CONF_NET_MANAGER_ENABLED                         CONF_NET_MANAGER_FUNC_ENABLED_VAL
#define _CONF_NET_INTERFACE_ENABLED                       CONF_NET_MANAGER_FUNC_ENABLED_VAL
#define _CONF_NET_INTERFACE_FACTORY_ENABLED               CONF_NET_MANAGER_FUNC_ENABLED_VAL

// wifi
#ifdef __CONF_NET_WIFI_FUNC_ENABLED
#define CONF_NET_WIFI_FUNC_ENABLED_VAL                    1
#else // __CONF_NET_WIFI_FUNC_ENABLED
#define CONF_NET_WIFI_FUNC_ENABLED_VAL                    0
#endif // __CONF_NET_WIFI_FUNC_ENABLED

#define _CONF_NET_WIFI_DEFINITION_ENABLED                 CONF_NET_WIFI_FUNC_ENABLED_VAL
#define _CONF_NET_WIFI_CONSTANT_ENABLED                   CONF_NET_WIFI_FUNC_ENABLED_VAL
#define _CONF_NET_WIFI_ENABLED                            CONF_NET_WIFI_FUNC_ENABLED_VAL
#define _CONF_NET_WIFI_AP_ENABLED                         CONF_NET_WIFI_FUNC_ENABLED_VAL
#define _CONF_NET_WIFI_STA_ENABLED                        CONF_NET_WIFI_FUNC_ENABLED_VAL

// http
#ifdef __CONF_COMM_HTTP_FUNC_ENABLED
#define CONF_COMM_HTTP_FUNC_ENABLED_VAL                   1
#else // __CONF_COMM_HTTP_FUNC_ENABLED
#define CONF_COMM_HTTP_FUNC_ENABLED_VAL                   0
#endif // __CONF_COMM_HTTP_FUNC_ENABLED

#define _CONF_COMM_HTTP_CONSTANT_ENABLED                  CONF_COMM_HTTP_FUNC_ENABLED_VAL
#define _CONF_COMM_HTTP_ENABLED                           CONF_COMM_HTTP_FUNC_ENABLED_VAL
#define _CONF_COMM_HTTP_CLIENT_ENABLED                    CONF_COMM_HTTP_FUNC_ENABLED_VAL
#define _CONF_COMM_HTTP_SERVER_ENABLED                    CONF_COMM_HTTP_FUNC_ENABLED_VAL

// mbc http
#ifdef __CONF_COMM_MBC_HTTP_FUNC_ENABLED
#define CONF_COMM_MBC_HTTP_FUNC_ENABLED_VAL               1
#else // __CONF_COMM_MBC_HTTP_FUNC_ENABLED
#define CONF_COMM_MBC_HTTP_FUNC_ENABLED_VAL               0
#endif // __CONF_COMM_MBC_HTTP_FUNC_ENABLED

#define _CONF_COMM_MBC_HTTP_CONSTANT_ENABLED              CONF_COMM_MBC_HTTP_FUNC_ENABLED_VAL
#define _CONF_COMM_MBC_HTTP_ENABLED                       CONF_COMM_MBC_HTTP_FUNC_ENABLED_VAL
#define _CONF_COMM_MBC_HTTP_CLIENT_ENABLED                CONF_COMM_MBC_HTTP_FUNC_ENABLED_VAL
#define _CONF_COMM_MBC_HTTP_SERVER_ENABLED                CONF_COMM_MBC_HTTP_FUNC_ENABLED_VAL


// ex comm
#ifdef __CONF_EX_COMM_FUNC_ENABLED
#define CONF_EX_COMM_FUNC_ENABLED_VAL                     1
#else // __CONF_EX_COMM_FUNC_ENABLED
#define CONF_EX_COMM_FUNC_ENABLED_VAL                     0
#endif // __CONF_EX_COMM_FUNC_ENABLED

#define _CONF_EX_COMM_CONSTANT_ENABLED                    CONF_EX_COMM_FUNC_ENABLED_VAL
#define _CONF_EX_COMM_MANAGER_ENABLED                     CONF_EX_COMM_FUNC_ENABLED_VAL


// main controller
#ifdef __CONF_MAIN_CONTROLLER_FUNC_ENABLED
#define CONF_MAIN_CONTROLLER_FUNC_ENABLED_VAL             1
#else // __CONF_MAIN_CONTROLLER_FUNC_ENABLED
#define CONF_MAIN_CONTROLLER_FUNC_ENABLED_VAL             0
#endif // __CONF_MAIN_CONTROLLER_FUNC_ENABLED

#define _CONF_MAIN_CONTROLLER_CONSTANT_ENABLED            CONF_MAIN_CONTROLLER_FUNC_ENABLED_VAL
#define _CONF_MAIN_CONTROLLER_ENABLED                     CONF_MAIN_CONTROLLER_FUNC_ENABLED_VAL
#define _CONF_MAIN_CONTROLLER_FACTORY_ENABLED             CONF_MAIN_CONTROLLER_FUNC_ENABLED_VAL
#define _CONF_MAIN_RESET_CONTROLLER_ENABLED               CONF_MAIN_CONTROLLER_FUNC_ENABLED_VAL
#define _CONF_MAIN_SETTING_CONTROLLER_ENABLED             CONF_MAIN_CONTROLLER_FUNC_ENABLED_VAL
#define _CONF_MAIN_NORMAL_CONTROLLER_ENABLED              CONF_MAIN_CONTROLLER_FUNC_ENABLED_VAL

// ui manager
#ifdef __CONF_UI_MANAGER_FUNC_ENABLED
#define CONF_UI_MANAGER_FUNC_ENABLED_VAL                  1
#else // __CONF_UI_MANAGER_FUNC_ENABLED
#define CONF_UI_MANAGER_FUNC_ENABLED_VAL                  0
#endif // __CONF_UI_MANAGER_FUNC_ENABLED

#define _CONF_UI_MANAGER_CONSTANT_ENABLED                 CONF_UI_MANAGER_FUNC_ENABLED_VAL
#define _CONF_UI_MANAGER_ENABLED                          CONF_UI_MANAGER_FUNC_ENABLED_VAL
#define _CONF_UI_CONTROL_TASK_ENABLED                     CONF_UI_MANAGER_FUNC_ENABLED_VAL
#define _CONF_UI_DP_PROCESSOR_ENABLED                     CONF_UI_MANAGER_FUNC_ENABLED_VAL
#define _CONF_UI_DP_PROCESSOR_FACTORY_ENABLED             CONF_UI_MANAGER_FUNC_ENABLED_VAL
#define _CONF_UI_DP_LCD_PROCESSOR_ENABLED                 CONF_UI_MANAGER_FUNC_ENABLED_VAL
#define _CONF_UI_DP_LCD_I2C_PROCESSOR_ENABLED             CONF_UI_MANAGER_FUNC_ENABLED_VAL
#define _CONF_UI_DP_SC_PROCESSOR_ENABLED                  CONF_UI_MANAGER_FUNC_ENABLED_VAL
#define _CONF_UI_DP_JMD_PROCESSOR_ENABLED                 CONF_UI_MANAGER_FUNC_ENABLED_VAL

// task scanning
#ifdef __CONF_TASK_SCANNING_FUNC_ENABLED
#define CONF_TASK_SCANNING_FUNC_ENABLED_VAL               1
#else // __CONF_TASK_SCANNING_FUNC_ENABLED
#define CONF_TASK_SCANNING_FUNC_ENABLED_VAL               0
#endif // __CONF_TASK_SCANNING_FUNC_ENABLED

#define _CONF_SCANNING_TASK_CONSTANT_ENABLED              CONF_TASK_SCANNING_FUNC_ENABLED_VAL
#define _CONF_SCANNING_SETTING_DEFINITION_ENABLED         CONF_TASK_SCANNING_FUNC_ENABLED_VAL
#define _CONF_SCANNING_CONTROLLER_ENABLED                 CONF_TASK_SCANNING_FUNC_ENABLED_VAL
#define _CONF_SCANNING_CONTROLLER_FACTORY_ENABLED         CONF_TASK_SCANNING_FUNC_ENABLED_VAL
#define _CONF_SCANNING_EV_CONTROLLER_ENABLED              CONF_TASK_SCANNING_FUNC_ENABLED_VAL
#define _CONF_SCANNING_CONTROL_TASK_ENABLED               CONF_TASK_SCANNING_FUNC_ENABLED_VAL


// task switch
#ifdef __CONF_TASK_SWITCH_FUNC_ENABLED
#define CONF_TASK_SWITCH_FUNC_ENABLED_VAL                 1
#else // __CONF_TASK_SWITCH_FUNC_ENABLED
#define CONF_TASK_SWITCH_FUNC_ENABLED_VAL                 0
#endif // __CONF_TASK_SCANNING_FUNC_ENABLED

#define _CONF_TASK_SWITCH_CONSTANT_ENABLED                CONF_TASK_SWITCH_FUNC_ENABLED_VAL
#define _CONF_SWITCH_MANAGER_ENABLED                      CONF_TASK_SWITCH_FUNC_ENABLED_VAL

// task button
#ifdef __CONF_TASK_BUTTON_FUNC_ENABLED
#define CONF_TASK_BUTTON_FUNC_ENABLED_VAL                 1
#else // __CONF_TASK_BUTTON_FUNC_ENABLED
#define CONF_TASK_BUTTON_FUNC_ENABLED_VAL                 0
#endif // __CONF_TASK_BUTTON_FUNC_ENABLED

#define _CONF_TASK_BUTTON_CONSTANT_ENABLED                CONF_TASK_BUTTON_FUNC_ENABLED_VAL
#define _CONF_BUTTON_MANAGER_ENABLED                      CONF_TASK_BUTTON_FUNC_ENABLED_VAL
/////////////////////////////////////////////////
// DEFINE

/////////////////////////////////////////////////
// GLOBAL VARIABLES

/////////////////////////////////////////////////
// GLOBAL FUNCTIONS

/////////////////////////////////////////////////
// DATA TYPE (TYPEDEF)

/////////////////////////////////////////////////
// DATA TYPE (ENUM)

/////////////////////////////////////////////////
// DATA TYPE (STRUCT)

/////////////////////////////////////////////////
// STATIC DATA

/////////////////////////////////////////////////
// STATIC FUNCTIONS
//

/////////////////////////////////////////////////
// EXTERN

/////////////////////////////////////////////////
// CLASS DEFINITION



#endif // _FLASH_EYES_MAIN_CONFIG_H