#ifndef _FLASH_EYES_CORE_TEST_CONFIG_H
#define _FLASH_EYES_CORE_TEST_CONFIG_H

/////////////////////////////////////////////////
// INCLUDE
// 
/////////////////////////////////////////////////
// PREPROCESSOR
// 
// 

//#define __CONF_TEST_CRITICAL_SESSION_FUNC_ENABLED
//#define __CONF_TEST_SYSTEM_LIGHT_QUEUE_FUNC_ENABLED
//#define __CONF_TEST_SYSTEM_MUTEX_LOCKER_FUNC_ENABLED
//#define __CONF_TEST_SYSTEM_MUTEX_NOTIFY_FUNC_ENABLED
//#define __CONF_TEST_TASK_LOGGING_FUNC_ENABLED
//#define __CONF_TEST_TASK_MANAGER_FUNC_ENABLED
//#define __CONF_TEST_TASK_COMM_SERIAL_FUNC_ENABLED
//#define __CONF_TEST_TASK_COMM_MBC_SERIAL_FUNC_ENABLED
//#define __CONF_TEST_TASK_COMM_I2C_SERVER_FUNC_ENABLED
//#define __CONF_TEST_TASK_COMM_I2C_CLIENT_FUNC_ENABLED
//#define __CONF_TEST_TASK_COMM_MBC_I2C_SERVER_FUNC_ENABLED
//#define __CONF_TEST_TASK_COMM_MBC_I2C_CLIENT_FUNC_ENABLED
#define __CONF_TEST_TIMER_MANAGER_FUNC_ENABLED
#define __CONF_TEST_OP_CODE_INPUT_FUNC_ENABLED

#ifdef __CONF_TEST_CRITICAL_SESSION_FUNC_ENABLED
#define _CONF_TEST_CRITICAL_SESSION_ENABLED
#endif // __CONF_TEST_CRITICAL_SESSION_FUNC_ENABLED

#ifdef __CONF_TEST_SYSTEM_LIGHT_QUEUE_FUNC_ENABLED
#define _CONF_TEST_SYSTEM_LIGHT_QUEUE_ENABLED
#endif // __CONF_TEST_SYSTEM_LIGHT_QUEUE_FUNC_ENABLED

#ifdef __CONF_TEST_SYSTEM_MUTEX_LOCKER_FUNC_ENABLED
#define _CONF_TEST_SYSTEM_MUTEX_LOCKER_ENABLED
#endif // __CONF_TEST_SYSTEM_MUTEX_LOCKER_FUNC_ENABLED

#ifdef __CONF_TEST_SYSTEM_MUTEX_NOTIFY_FUNC_ENABLED
#define _CONF_TEST_SYSTEM_MUTEX_NOTIFY_ENABLED
#endif // __CONF_TEST_SYSTEM_MUTEX_NOTIFY_FUNC_ENABLED

#ifdef __CONF_TEST_TASK_MANAGER_FUNC_ENABLED
#define _CONF_TEST_TASK_MANAGER_ENABLED
#endif // __CONF_TEST_TASK_MANAGER_FUNC_ENABLED

#ifdef __CONF_TEST_TASK_COMM_MBC_SERIAL_FUNC_ENABLED
#define _CONF_TEST_TASK_COMM_MBC_SERIAL_ENABLED
#endif // __CONF_TEST_TASK_COMM_MBC_SERIAL_FUNC_ENABLED


#ifdef __CONF_TEST_TASK_COMM_SERIAL_FUNC_ENABLED
#define _CONF_TEST_TASK_COMM_SERIAL_ENABLED
#endif // __CONF_TEST_TASK_COMM_SERIAL_FUNC_ENABLED

#ifdef __CONF_TEST_TASK_COMM_I2C_SERVER_FUNC_ENABLED
#define _CONF_TEST_TASK_COMM_I2C_SERVER_ENABLED
#endif // __CONF_TEST_TASK_COMM_I2C_SERVER_FUNC_ENABLED

#ifdef __CONF_TEST_TASK_COMM_I2C_CLIENT_FUNC_ENABLED
#define _CONF_TEST_TASK_COMM_I2C_CLIENT_ENABLED
#endif // __CONF_TEST_TASK_COMM_I2C_CLIENT_FUNC_ENABLED

#ifdef __CONF_TEST_TASK_COMM_MBC_I2C_SERVER_FUNC_ENABLED
#define _CONF_TEST_TASK_COMM_MBC_I2C_SERVER_ENABLED
#endif // __CONF_TEST_TASK_COMM_MBC_I2C_SERVER_FUNC_ENABLED

#ifdef __CONF_TEST_TASK_COMM_MBC_I2C_CLIENT_FUNC_ENABLED
#define _CONF_TEST_TASK_COMM_MBC_I2C_CLIENT_ENABLED
#endif // __CONF_TEST_TASK_COMM_MBC_I2C_CLIENT_FUNC_ENABLED

#ifdef __CONF_TEST_OP_CODE_INPUT_FUNC_ENABLED
#define _CONF_TEST_OP_CODE_INPUT_ENABLED
#endif // __CONF_TEST_OP_CODE_INPUT_FUNC_ENABLED


/////////////////////////////////////////////////
// DEFINE

/////////////////////////////////////////////////
// GLOBAL VARIABLES

/////////////////////////////////////////////////
// GLOBAL FUNCTIONS

/////////////////////////////////////////////////
// DATA TYPE (TYPEDEF)

/////////////////////////////////////////////////
// DATA TYPE (ENUM)

/////////////////////////////////////////////////
// DATA TYPE (STRUCT)

/////////////////////////////////////////////////
// STATIC DATA

/////////////////////////////////////////////////
// STATIC FUNCTIONS
//

/////////////////////////////////////////////////
// EXTERN

/////////////////////////////////////////////////
// CLASS DEFINITION



#endif // _FLASH_EYES_CORE_TEST_CONFIG_H